my_string=('Верь в меня,верь в мою веру в себя')
simvols = len(my_string)
print("Количество символов:", simvols)
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ',''))
print(my_string[0])
print(my_string[-1])